### ISSUE TITLE
compile fails

### ISSUE THREAD

**Issue by marinonjalsson** [dalmatinerdb/ddb_client#5]
(I'm new to erlang and rebar)  

in the README.md there are information how to build the client using rebar3
but there is no rebar3 app as is in other repos.

make fails with rebar installed on my debian jessie box.

~/Download/ddb_client$ make
rebar get-deps
==> ddb_client (get-deps)
rebar compile
==> ddb_client (compile)
Dependency not available: dproto-~>0.2.0 (undefined)
Dependency not available: mmath-~>0.2.0 (undefined)
Dependency not available: snappy-~>1.1.1 (undefined)
Makefile:9: recipe for target 'compile' failed
make: *** [compile] Error 1

??

Best regards, Marinó

**Comment by marinonjalsson** [comment]
nevermind, worked it out. :)

**Comment by Licenser** [comment]
This is basically used as a library for other projects on it's own it's going to be pretty boring unless you just want to play around.

**Comment by Licenser** [comment]
cool! :D

**Comment by marinonjalsson** [comment]
The python client is now sending metrics to the dog. I'm reading them on
the frontend. :)

Tomorrow l will dump some millions of metrics to it. Very excited :)

Marino

**Comment by Licenser** [comment]
glad you like it :) if all goes well can I convince you to write a quick "how to get form 0 to 60 in 3 seconds"? Doesn't have to be flashy or long just what you did and how you got there, what to avoid and what to do. It's really hard for me to write something along those lines since I know all the little bumps and rough edges and avoid them instinctively.

**Comment by marinonjalsson** [comment]
I would like to contribute if all goes well :)

I'm stuck at the moment in figuring out the query interface,  I'm no erlang
dude so I'm trying out the dalmatinerfe+http+javascripts.

I'm trying to select 10 metrics points from 2015, SQL:   SELECT 'test_100'
BUCKET 'maeli_test' BETWEEN "2015-09-26T13:00:24Z" AND
"2015-09-28T13:00:24Z"

http://localhost:8080/?query=SELECT%20%27test_100%27%20BUCKET%20%27maeli_test%27%20BETWEEN%20%222015-09-26T13%3A00%3A24Z%22%20AND%20%222015-09-28T13%3A00%3A24Z%22

but the javascript comes unresponseive !!!!

---
I would like to build a python uwsgi web interface to the dalmatinerdb, and
from there some custom d3.js dashboards.  If only there was a python query
client.  The ddbpy from dataloop has no real query sql interface.

best regards, Marinó

**Comment by marinonjalsson** [comment]
ignor last mail :)
to much data,
the http-api will do just fine
